version: '3'

services:
  postgres:
    image: postgres:16
    env_file: ./db.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  funny_dolphine:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    network_mode: host
    env_file: ./env.list
    depends_on:
      - postgres

volumes:
  pg_data:
