"""chapter and user chapter

Revision ID: 08473aef612a
Revises: 1347aa4629a1
Create Date: 2024-01-09 15:56:50.256736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "08473aef612a"
down_revision: Union[str, None] = "1347aa4629a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chapter",
        sa.Column("chapter_id", sa.Integer(), nullable=False),
        sa.Column("chapter_ordered_id", sa.Integer(), nullable=False),
        sa.Column("audiobook_id", sa.Integer(), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("sub_title", sa.String(length=120), nullable=False),
        sa.Column("full_text", sa.Text(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("audio_file_url", sa.String(length=2048), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["audiobook_id"],
            ["audiobook.audiobook_id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["chapter.chapter_id"],
        ),
        sa.PrimaryKeyConstraint("chapter_id"),
    )
    op.create_index(
        op.f("ix_chapter_chapter_id"), "chapter", ["chapter_id"], unique=False
    )
    op.create_index(
        op.f("ix_chapter_chapter_ordered_id"),
        "chapter",
        ["chapter_ordered_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chapter_sub_title"), "chapter", ["sub_title"], unique=False
    )
    op.create_table(
        "user_chapter",
        sa.Column("user_chapter_id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("chapter_id", sa.Integer(), nullable=True),
        sa.Column("explored", sa.Boolean(), nullable=True),
        sa.Column("listened_times", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.account_id"],
        ),
        sa.ForeignKeyConstraint(
            ["chapter_id"],
            ["chapter.chapter_id"],
        ),
        sa.PrimaryKeyConstraint("user_chapter_id"),
    )
    op.create_index(
        op.f("ix_user_chapter_user_chapter_id"),
        "user_chapter",
        ["user_chapter_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_chapter_user_chapter_id"), table_name="user_chapter")
    op.drop_table("user_chapter")
    op.drop_index(op.f("ix_chapter_sub_title"), table_name="chapter")
    op.drop_index(op.f("ix_chapter_chapter_ordered_id"), table_name="chapter")
    op.drop_index(op.f("ix_chapter_chapter_id"), table_name="chapter")
    op.drop_table("chapter")
    # ### end Alembic commands ###
