"""created reviews table

Revision ID: 13c471472fae
Revises: 7c70c2bca38f
Create Date: 2024-01-19 21:24:21.504487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13c471472fae'
down_revision: Union[str, None] = '7c70c2bca38f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('audiobook_id', sa.Integer(), nullable=False),
    sa.Column('rating_value', sa.Integer(), nullable=False),
    sa.Column('rating_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('review_content', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ),
    sa.ForeignKeyConstraint(['audiobook_id'], ['audiobook.audiobook_id'], ),
    sa.PrimaryKeyConstraint('account_id', 'audiobook_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    # ### end Alembic commands ###
