"""create salt and login table

Revision ID: 1dc3739ccc1d
Revises: e8fff70a5889
Create Date: 2024-01-25 21:00:03.868489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1dc3739ccc1d"
down_revision: Union[str, None] = "e8fff70a5889"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "loginMethod",
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("login_email", sa.String(), nullable=False),
        sa.Column("login_password", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.account_id"],
        ),
        sa.PrimaryKeyConstraint("account_id"),
        sa.UniqueConstraint("login_email"),
    )
    op.create_table(
        "salt",
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("salt", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.account_id"],
        ),
        sa.PrimaryKeyConstraint("account_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("salt")
    op.drop_table("loginMethod")
    # ### end Alembic commands ###
