"""review and listening tables

Revision ID: e8fff70a5889
Revises: 7c70c2bca38f
Create Date: 2024-01-20 16:53:27.260031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8fff70a5889'
down_revision: Union[str, None] = '7c70c2bca38f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('audiobook_id', sa.Integer(), nullable=False),
    sa.Column('rating_value', sa.Integer(), nullable=False),
    sa.Column('rating_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('review_content', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ),
    sa.ForeignKeyConstraint(['audiobook_id'], ['audiobook.audiobook_id'], ),
    sa.PrimaryKeyConstraint('account_id', 'audiobook_id')
    )
    op.create_table('listening',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('audiobook_id', sa.Integer(), nullable=False),
    sa.Column('current_chapter_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('last_access_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('finish_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ),
    sa.ForeignKeyConstraint(['audiobook_id'], ['audiobook.audiobook_id'], ),
    sa.ForeignKeyConstraint(['current_chapter_id'], ['chapter.chapter_id'], ),
    sa.PrimaryKeyConstraint('account_id', 'audiobook_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listening')
    op.drop_table('review')
    # ### end Alembic commands ###
