"""create listening table

Revision ID: f405349eee0d
Revises: 13c471472fae
Create Date: 2024-01-20 15:04:19.078636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f405349eee0d'
down_revision: Union[str, None] = '13c471472fae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listening',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('audiobook_id', sa.Integer(), nullable=False),
    sa.Column('current_chapter_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('last_access_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('finish_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ),
    sa.ForeignKeyConstraint(['audiobook_id'], ['audiobook.audiobook_id'], ),
    sa.ForeignKeyConstraint(['current_chapter_id'], ['chapter.chapter_id'], ),
    sa.PrimaryKeyConstraint('account_id', 'audiobook_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listening')
    # ### end Alembic commands ###
